version: '3.8'
services:

  transaction_service:
    build:
      context: .
      dockerfile: ./service4/Dockerfile
    ports:
      - "8004:8004"
  
  mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: helpdev
            MONGO_INITDB_ROOT_PASSWORD: 123456
            ME_CONFIG_MONGODB_ADMINUSERNAME: helpdev
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            MONGO_INITDB_DATABASE: bank
            
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ./data_features_rf.json:/tmp/data_features_rf.json:ro

  # Database Manager
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: helpdev
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_AUTH_DATABASE: bank
      ME_CONFIG_MONGODB_SERVER: mongodb
    #links:
    #  - mongodb
  
  orchestration_service:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    ports:
      - "8001:8001"
   
  db_service:
    build:
      context: .
      dockerfile: ./service3/Dockerfile
    ports:
      - "8003:8003"
    environment:
        MONGODB_HOST: mongodb