version: '3.8'
services:

  transaction_service:
    image: roobsonsants/postgree_docker-transaction_service:latest
    ports:
      - "8004:8004"
    environment:
      OTEL_SERVICE_NAME: "transaction"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
    depends_on:
      - collector

  mongodb:
        image: mongo:latest
        container_name: mongo-server
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: helpdev
            MONGO_INITDB_ROOT_PASSWORD: 123456
            ME_CONFIG_MONGODB_ADMINUSERNAME: helpdev
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            MONGO_INITDB_DATABASE: bank
            
        ports:
            - 27017:27017
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
            - ./data_features_rf.json:/tmp/data_features_rf.json:ro

  orchestration_service:
    image: roobsonsants/postgree_docker-orchestration_service:latest
    ports:
      - "8001:8001"
    environment:
      OTEL_SERVICE_NAME: "orchestration"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
    depends_on:
      - collector
   
  db_service:
    image: roobsonsants/postgree_docker-db_service:latest
    ports:
      - "8003:8003"
    environment:
      MONGODB_HOST: mongodb
      OTEL_SERVICE_NAME: "db"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:4317"
    depends_on:
      - collector


  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    volumes:
      - ./otel-config.yml:/otel-config.yml
    command: ["--config=/otel-config.yml"]
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317" # otlp receiver
    depends_on:
      - jaeger