FROM python:3.14.0a1-slim

WORKDIR /service1

COPY requirements.txt ./

RUN apt-get update && apt-get install -y libpq-dev

#RUN pip install --no-cache-dir psycopg2-binary

#RUN pip install xgboost

RUN pip install -r ./requirements.txt
#RUN pip install fastapi uvicorn

COPY . .

CMD uvicorn service1.main:app --host 0.0.0.0 --port 8001 --reload
